/** 日志 Guest 文档：无 React；浏览器载入 iframe，Tauri 载入 child WebView。 */

export const LOGS_PANE_ID = "logs";

export const LOGS_PANE_HTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>日志</title><style>
:root{color-scheme:light dark}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{display:flex;flex-direction:column;background:hsl(var(--background,0 0% 100%));color:hsl(var(--foreground,0 0% 9%));font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace}
header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 10px;border-bottom:1px solid hsl(var(--border,0 0% 89%));flex:none;font-weight:600}
#status{color:hsl(var(--muted-foreground,0 0% 45%));font-weight:400;font-size:11px}#controls{display:flex;gap:6px;padding:7px 10px;border-bottom:1px solid hsl(var(--border,0 0% 89%));flex:none}
select,input{min-width:0;height:26px;border:1px solid hsl(var(--border,0 0% 89%));border-radius:4px;background:hsl(var(--muted,0 0% 96%));color:inherit;padding:3px 6px;font:inherit}select{width:78px}input{flex:1}
#list{list-style:none;overflow:auto;flex:1;margin:0;padding:4px 0}.row{display:flex;gap:7px;align-items:baseline;padding:2px 10px}.row:hover{background:hsl(var(--accent,0 0% 96%))}.ts{color:hsl(var(--muted-foreground,0 0% 45%));flex:none}.level{width:38px;flex:none;font-weight:700}.ns{max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:hsl(var(--muted-foreground,0 0% 45%));flex:none}.msg{min-width:0;overflow-wrap:anywhere}.debug{color:hsl(var(--muted-foreground,0 0% 45%))}.info{color:hsl(var(--primary,0 0% 9%))}.warn{color:light-dark(#a16207,#fcd34d)}.error{color:hsl(var(--destructive,0 84% 60%))}
</style></head><body><header><span>日志 <span id="count"></span></span><span id="status">正在连接…</span></header>
<div id="controls"><select id="level" aria-label="最低级别"><option value="debug">debug</option><option value="info">info</option><option value="warn">warn</option><option value="error">error</option></select><input id="namespace" placeholder="命名空间"><input id="search" placeholder="搜索"></div>
<ul id="list" data-pi-logs-region></ul><script>
(function(){
  var port,seq=0,entries=new Map(),level=document.getElementById('level'),namespace=document.getElementById('namespace'),search=document.getElementById('search'),list=document.getElementById('list'),count=document.getElementById('count'),status=document.getElementById('status');
  var ranks={debug:0,info:1,warn:2,error:3};
  function applyTheme(theme){if(!theme||typeof theme!=='object')return;var root=document.documentElement,tokens=theme.tokens;if(tokens&&typeof tokens==='object')Object.keys(tokens).forEach(function(name){if(name.indexOf('--')===0)root.style.setProperty(name,String(tokens[name]))});if(theme.colorScheme==='light'||theme.colorScheme==='dark')root.style.colorScheme=theme.colorScheme}
  function paint(){var min=ranks[level.value]||0,ns=namespace.value,q=search.value,rows=[];entries.forEach(function(e){if(ranks[e.level]<min)return;if(ns&&e.ns!==ns&&e.ns.indexOf(ns+':')!==0)return;if(q&&String(e.msg).indexOf(q)<0)return;rows.push(e)});rows.sort(function(a,b){return(a.ts||0)-(b.ts||0)});list.replaceChildren();count.textContent=rows.length?'· '+rows.length:'';rows.forEach(function(e){var li=document.createElement('li');li.className='row';var ts=document.createElement('span');ts.className='ts';ts.textContent=new Date(e.ts||0).toLocaleTimeString();var lv=document.createElement('span');lv.className='level '+(e.level||'debug');lv.textContent=String(e.level||'debug').toUpperCase();var n=document.createElement('span');n.className='ns';n.title=e.ns||'';n.textContent=e.ns||'';var m=document.createElement('span');m.className='msg';m.textContent=String(e.msg||'');li.append(ts,lv,n,m);list.append(li)})}
  function query(){if(!port)return;var id='logs-'+(++seq);port.postMessage({type:'pane:request',requestId:id,operation:'route.query',route:'session.logs',query:{limit:'500'}})}
  function connect(event){var d=event.data;if(event.source!==parent||!d||d.type!=='pane:connected'||d.protocol!==1||!event.ports||event.ports.length!==1||!d.instance||d.instance.paneId!=='logs')return;applyTheme(d.theme);port=event.ports[0];port.onmessage=function(message){var data=message.data;if(!data)return;if(data.type==='pane:theme'){applyTheme(data.theme);return}if(data.type!=='pane:result')return;if(!data.ok){status.textContent='日志读取失败';return}var body=data.data,listData=Array.isArray(body)?body:(body&&Array.isArray(body.entries)?body.entries:[]);listData.forEach(function(e){if(e&&typeof e.id==='string')entries.set(e.id,e)});status.textContent='已连接';paint()};port.start&&port.start();query();setInterval(query,1000)}
  window.addEventListener('message',connect);window.parent.postMessage({type:'pane:ready',protocol:1,paneId:'logs'},'*');level.addEventListener('change',paint);namespace.addEventListener('input',paint);search.addEventListener('input',paint);
})();</script></body></html>`;
