/**
 * 构建 aigc-canvas-agent 的 pane 文档与 webext 产物。
 *
 * 两步:
 *  1. esbuild 把 `web/panes/canvas.tsx` 打成自足 IIFE,连同 canvas-ui 的 Tailwind CSS
 *     内联进一份 HTML,写成 `web/pane-documents.generated.ts`;
 *  2. `buildWebExtension` 把 `web/` 打成 `.pi/web/dist/`(注册表与运行时载入的产物)。
 *
 * ★ 第 1 步的产物**构建完就删**(finally 里 rm)。它不入库,也就不可能出现
 *   「本地绿是因为工作树里躺着一份没人生成的产物」—— 本会话已在三处踩过这个坑
 *   (webext 示例产物、兄弟仓、声明式夹具)。类型侧由 `web/pane-documents.generated.d.ts`
 *   垫片兜住,故 typecheck 不依赖构建产物。
 *
 * CSP:pane 文档只允许内联 style/script,图片放开到 blob:/data:/http(s):(画廊要显示
 * 附件签名 URL 与本地 blob 预览),其余一律 `default-src 'none'`。
 */
import { build } from "esbuild";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildWebExtension, type BuildResult } from "@blksails/pi-web-kit/build";
import postcss from "postcss";
import tailwindcss from "tailwindcss";
import type { Config } from "tailwindcss";
import { piWebPreset } from "../../packages/ui/tailwind-preset.js";

const ROOT = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(ROOT, "..", "..");

/** 画廊自身的基础样式:iframe 里没有宿主的 body 样式,得自带高度与配色基线。 */
const PANE_BASE_CSS = String.raw`
html,body,#root{height:100%;margin:0}
body{background:hsl(var(--background));color:hsl(var(--foreground))}
*{box-sizing:border-box}
`;

async function buildCanvasCss(): Promise<string> {
  const config: Config = {
    presets: [piWebPreset as Config],
    content: [
      resolve(ROOT, "web", "panes", "canvas.tsx"),
      resolve(REPO, "packages", "canvas-ui", "src", "**", "*.{ts,tsx}"),
      resolve(REPO, "packages", "canvas-kit", "src", "**", "*.{ts,tsx}"),
      resolve(REPO, "packages", "primitives", "src", "**", "*.{ts,tsx}"),
    ],
  };
  const generated = await postcss([tailwindcss(config)]).process(
    "@tailwind base; @tailwind components; @tailwind utilities;",
    { from: undefined },
  );
  const [uiStyles, canvasStyles] = await Promise.all([
    readFile(resolve(REPO, "packages", "ui", "src", "styles.css"), "utf8"),
    readFile(resolve(REPO, "packages", "canvas-ui", "src", "styles.css"), "utf8"),
  ]);
  return `${uiStyles}\n${canvasStyles}\n${generated.css}\n${PANE_BASE_CSS}`;
}

function htmlDocument(title: string, script: string, css: string): string {
  // `</script` 出现在 bundle 字面量里会提前闭合标签 —— 必须转义。
  const safeScript = script.replace(/<\/script/gi, "<\\/script");
  return (
    `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">` +
    `<meta name="viewport" content="width=device-width">` +
    `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src blob: data: http: https:; style-src 'unsafe-inline'; script-src 'unsafe-inline'">` +
    `<title>${title}</title><style>${css}</style></head>` +
    `<body><div id="root"></div><script>${safeScript}</script></body></html>`
  );
}

async function buildPaneDocuments(): Promise<string> {
  const css = await buildCanvasCss();
  const result = await build({
    entryPoints: [resolve(ROOT, "web", "panes", "canvas.tsx")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2022",
    jsx: "automatic",
    minify: true,
    legalComments: "none",
    define: { "process.env.NODE_ENV": '"production"' },
  });
  const output = result.outputFiles?.[0];
  if (output === undefined) throw new Error("canvas pane 未生成 bundle");
  const documents = { canvas: htmlDocument("画廊", output.text, css) };
  const target = resolve(ROOT, "web", "pane-documents.generated.ts");
  await writeFile(
    target,
    `// Generated by examples/aigc-canvas-agent/build.ts; do not edit.\nexport const paneDocuments = ${JSON.stringify(documents)} as const;\n`,
    "utf8",
  );
  return target;
}

export async function buildAigcCanvasAgent(): Promise<BuildResult> {
  const generated = await buildPaneDocuments();
  try {
    const outDir = resolve(ROOT, ".pi", "web", "dist");
    await mkdir(outDir, { recursive: true });
    return await buildWebExtension({
      id: "aigc-canvas",
      targetApiVersion: "^0.5.0",
      entryDir: resolve(ROOT, "web"),
      outDir,
      capabilities: ["slots", "config"],
    });
  } finally {
    await rm(generated, { force: true });
  }
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  void buildAigcCanvasAgent().then((result) =>
    // eslint-disable-next-line no-console
    console.log(`[built] aigc-canvas → ${result.entryOut}`),
  );
}
