/**
 * 构建 aigc-canvas-agent 的 pane 文档与 webext 产物。
 *
 * 两步:
 *  1. esbuild 把 `web/panes/canvas.tsx` 打成自足 IIFE,连同 canvas-ui 的 Tailwind CSS
 *     内联进一份 HTML,写成 `web/pane-documents.generated.ts`;
 *  2. `buildWebExtension` 把 `web/` 打成 `.pi/web/dist/`(注册表与运行时载入的产物)。
 *
 * ★ 第 1 步的产物**构建完就删**(finally 里 rm)。它不入库,也就不可能出现
 *   「本地绿是因为工作树里躺着一份没人生成的产物」—— 本会话已在三处踩过这个坑
 *   (webext 示例产物、兄弟仓、声明式夹具)。类型侧由 `web/pane-documents.generated.d.ts`
 *   垫片兜住,故 typecheck 不依赖构建产物。
 *
 * CSP:pane 文档只允许内联 style/script,图片放开到 blob:/data:/http(s):(画廊要显示
 * 附件签名 URL 与本地 blob 预览),其余一律 `default-src 'none'`。
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildWebExtension, type BuildResult } from "@blksails/pi-web-kit/build";
import { buildCanvasPaneDocument } from "@blksails/pi-web-canvas-ui/build/pane-document";

const ROOT = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(ROOT, "..", "..");

async function buildPaneDocuments(): Promise<string> {
  // ★ 流水线本身已抽到 canvas-ui/build(spec panes-only-right-panel 任务 1.5):
  // 内容安全策略、样式基线、`</script` 转义只有一份,不会与另一个 source 漂开。
  const documents = {
    canvas: await buildCanvasPaneDocument({
      repoRoot: REPO,
      entry: resolve(ROOT, "web", "panes", "canvas.tsx"),
      title: "画廊",
    }),
  };
  const target = resolve(ROOT, "web", "pane-documents.generated.ts");
  await writeFile(
    target,
    `// Generated by examples/aigc-canvas-agent/build.ts; do not edit.\nexport const paneDocuments = ${JSON.stringify(documents)} as const;\n`,
    "utf8",
  );
  return target;
}

export async function buildAigcCanvasAgent(): Promise<BuildResult> {
  const generated = await buildPaneDocuments();
  try {
    const outDir = resolve(ROOT, ".pi", "web", "dist");
    await mkdir(outDir, { recursive: true });
    return await buildWebExtension({
      id: "aigc-canvas",
      targetApiVersion: "^0.5.0",
      entryDir: resolve(ROOT, "web"),
      outDir,
      capabilities: ["slots", "config"],
    });
  } finally {
    await rm(generated, { force: true });
  }
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  void buildAigcCanvasAgent().then((result) =>
    // eslint-disable-next-line no-console
    console.log(`[built] aigc-canvas → ${result.entryOut}`),
  );
}
