/**
 * 构建 surface-demo-agent 的 pane 文档与 webext 产物。
 *
 * pane 文档经**通用层**(web-kit/build/pane-document)打出 —— 这个面板与画布无关,
 * 不必为构建一个 pane 依赖整个画布包。内容安全策略与基线样式由通用层统一提供。
 *
 * ★ 产物构建完即删(finally 里 rm),不入库 —— 避免「本地绿是因为工作树里躺着一份没人
 * 生成的产物」。类型侧由 `web/pane-documents.generated.d.ts` 垫片兜住。
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildWebExtension, type BuildResult } from "@blksails/pi-web-kit/build";
import { buildPaneDocument } from "@blksails/pi-web-kit/build/pane-document";

const ROOT = dirname(fileURLToPath(import.meta.url));

async function buildPaneDocuments(): Promise<string> {
  const documents = {
    demo: await buildPaneDocument({
      entry: resolve(ROOT, "web", "panes", "demo.tsx"),
      title: "Demo Surface",
    }),
  };
  const target = resolve(ROOT, "web", "pane-documents.generated.ts");
  await writeFile(
    target,
    `// Generated by examples/surface-demo-agent/build.ts; do not edit.\nexport const paneDocuments = ${JSON.stringify(documents)} as const;\n`,
    "utf8",
  );
  return target;
}

export async function buildSurfaceDemoAgent(): Promise<BuildResult> {
  const generated = await buildPaneDocuments();
  try {
    const outDir = resolve(ROOT, ".pi", "web", "dist");
    await mkdir(outDir, { recursive: true });
    return await buildWebExtension({
      id: "surface-demo",
      targetApiVersion: "^0.5.0",
      entryDir: resolve(ROOT, "web"),
      outDir,
      capabilities: [],
    });
  } finally {
    await rm(generated, { force: true });
  }
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  void buildSurfaceDemoAgent().then((result) =>
    // eslint-disable-next-line no-console
    console.log(`[built] surface-demo → ${result.entryOut}`),
  );
}
